---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploy
  namespace: jenkins
spec:
  replicas: 2
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      labels:
        env: dev
    spec:
      containers:
        - name: app-cont
          image: meher27/assignment:appimage
          ports:
            - containerPort: 3000


---
apiVersion: v1
kind: Service
metadata:
  name: mysvc
  namespace: jenkins
spec:
  type: LoadBalancer
  selector:
    env: dev
  ports:
    - port: 3000
      targetPort: 3000
  
      
